" colorscheme generated by ColorSchemeEditor.py
"Name: mars_test
"Maintainer: erik falor <efalor@gmail.com>
"Version: 1.0
"Last Change: 2008 Mar 01
"URL: http://www.vim.org/scripts/script.php?script_id=1234
"License: and by the ghosts of Mars
"Licensed under the Vim license

"Notes:     - Thanks to Raimon Grau for his feedback
"    * Place :colo mars in your .VimRC/GVimRC file
"    * GvimRC if using GUI any
"    - Thanks to Desert and OceanDeep for their color scheme
"    file layouts


set background=dark
if version > 580
	highlight clear
	if exists("syntax_on")
		syntax reset
	endif
endif
let g:colors_name = "mars_test"

if v:version >= 700
	highlight CursorColumn guibg=#0000FF
	highlight CursorLine guibg=#0000FF
	highlight Pmenu guibg=Magenta
	highlight PmenuSel guibg=DarkGrey
	highlight PmenuSbar guibg=Grey
	highlight PmenuThumb gui=reverse
	highlight SpellBad gui=undercurl
	highlight SpellCap gui=undercurl
	highlight SpellLocal gui=undercurl
	highlight SpellRare gui=undercurl
	highlight TabLine guibg=DarkGrey gui=underline
	highlight TabLineFill gui=reverse
	highlight TabLineSel gui=bold
endif
highlight Cursor guifg=#A0963C guibg=#FFFFFF
highlight CursorIM guifg=#6699CC guibg=#99CCCC
highlight Directory guifg=#B45000 guibg=#961E00
highlight DiffAdd guifg=#FFFFCC guibg=#961E00
highlight DiffChange guifg=#FF9900 guibg=#961E00
highlight DiffDelete guifg=#999999 guibg=#961E00 gui=bold
highlight DiffText guifg=#FFFFFF guibg=#961E00 gui=bold
highlight ErrorMsg guifg=#FFFFFF guibg=#FF0000
highlight VertSplit guifg=#FFFFFF guibg=#961E00 gui=reverse
highlight Folded guifg=#999999 guibg=#BE1E00 gui=italic
highlight FoldColumn guifg=#CC0000 guibg=#999999
highlight SignColumn guifg=#229696 guibg=Grey
highlight IncSearch guifg=#FFFF00 guibg=#961E00 gui=reverse
highlight LineNr guifg=#999999 guibg=#BE1E00
highlight MoreMsg guifg=#FFFFFF guibg=#961E00 gui=bold
highlight NonText guifg=#FFFFFF guibg=#A0141E gui=bold
highlight Normal guifg=#FFFFFF guibg=#961E00
highlight Question guifg=#FFFFFF guibg=#EE0000 gui=bold
highlight Search guifg=#A0142B guibg=#FFFF00 gui=underline
highlight SpecialKey guifg=#FFFF00 guibg=#961E00
highlight StatusLine guifg=#FFFFFF guibg=#961E00 gui=bold,reverse
highlight StatusLineNC guifg=#CCCCCC guibg=#961E00 gui=reverse
highlight Title guifg=#FFFFFF guibg=#FF9900 gui=bold
highlight Visual guifg=#B45000 guibg=#961E00
highlight VisualNOS gui=bold,underline
highlight WarningMsg guifg=#FF0000 guibg=#FFFFFF
highlight WildMenu guifg=#961E00 guibg=#999999
highlight Comment guifg=#80a0ff
highlight Constant guifg=#ffa0a0
highlight Special guifg=Orange
highlight Identifier guifg=#40ffff
highlight Statement guifg=#ffff60 gui=bold
highlight PreProc guifg=#ff80ff
highlight Type guifg=#60ff60 gui=bold
highlight Underlined guifg=#80a0ff gui=underline
highlight Ignore guifg=bg
highlight Error guifg=White guibg=Red
highlight Todo guifg=Blue guibg=Yellow
highlight link String Constant
highlight link Character Constant
highlight link Number Constant
highlight link Boolean Constant
highlight link Float Number
highlight link Function Identifier
highlight link Conditional Statement
highlight link Repeat Statement
highlight link Label Statement
highlight link Operator Statement
highlight link Keyword Statement
highlight link Exception Statement
highlight link Include PreProc
highlight link Define PreProc
highlight link Macro PreProc
highlight link PreCondit PreProc
highlight link StorageClass Type
highlight link Structure Type
highlight link Typedef Type
highlight link Tag Special
highlight link SpecialChar Special
highlight link Delimiter Special
highlight link SpecialComment Special
highlight link Debug Special


"ColorScheme metadata{{{
let g:mars_test_Metadata = {
            \"Palette" : "#E8DF29:#FFF300:#7F7F7F:#FF0000:#A020F0:#0000FF:#ADD8E6:#00FF00:#FFFF00:#FFA500:#E6E6FA:#A52A2A:#8B6914:#1E90FF:#FFC0CB:#90EE90:#1A1A1A:#4D4D4D:#BFBFBF:#E5E5E5",
            \"Maintainer" : "erik falor",
            \"Name" : "mars_test",
            \"Last Change" : "2008 Mar 01",
            \"URL" : "http://www.vim.org/scripts/script.php?script_id=1234",
            \"Notes" : ["    * Place :colo mars in your .VimRC/GVimRC file",
                \"    * GvimRC if using GUI any",
                \"    - Thanks to Desert and OceanDeep for their color scheme",
                \"    file layouts",
                \"    - Thanks to Raimon Grau for his feedback"],
            \"License" : ["Licensed under the Vim license",
                \"and by the ghosts of Mars"],
            \"Version" : "1.0",
            \"Email" : "efalor@gmail.com",
            \}
"}}}
" vim:set foldmethod=marker expandtab filetype=vim:
